name: tests

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4]
        laravel: [^7.0]
    name: P${{ matrix.php }} - L${{ matrix.laravel }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip
        coverage: none
    - name: Create Laravel app
      run: composer create-project laravel/laravel=${{ matrix.laravel }} ../app --prefer-dist
    - name: Install dependencies
      run: |
        cd ../app
        composer config repositories.local '{"type": "path", "url": "../ttall"}' --file composer.json
        composer require pktharindu/ttall @dev
        composer update
    - name: Install preset
      run: |
        cd ../app
        php artisan ui ttall --auth --option=code-helpers
    - name: Execute tests
      run: |
        cd ../app
        vendor/bin/phpunit --verbose
